<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" tests="22" skipped="0" failures="0" errors="0" timestamp="2021-03-19T10:46:52" hostname="Dream.local" time="2.327">
  <properties/>
  <testcase name="scheduleOneTimeFailingTaskWithErrorHandler" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.001"/>
  <testcase name="submitFailingRunnableWithErrorHandler" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.001"/>
  <testcase name="scheduleMultipleTriggerTasks" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.026"/>
  <testcase name="executeFailingRunnableWithErrorHandler" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.0"/>
  <testcase name="submitFailingCallableWithErrorHandler" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.001"/>
  <testcase name="scheduleOneTimeTask" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.0"/>
  <testcase name="scheduleOneTimeFailingTaskWithoutErrorHandler" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.009"/>
  <testcase name="scheduleTriggerTask" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.0"/>
  <testcase name="submitCallableWithGetAfterShutdown" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.001"/>
  <testcase name="submitListenableCallableWithGetAfterShutdown" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.003"/>
  <testcase name="submitListenableCallable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.106"/>
  <testcase name="executeRunnable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.012"/>
  <testcase name="submitListenableRunnable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="1.002"/>
  <testcase name="submitFailingCallable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.013"/>
  <testcase name="submitCallable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.013"/>
  <testcase name="submitFailingListenableCallable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.103"/>
  <testcase name="submitRunnableWithGetAfterShutdown" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.001"/>
  <testcase name="submitListenableRunnableWithGetAfterShutdown" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.001"/>
  <testcase name="submitFailingRunnable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.014"/>
  <testcase name="submitRunnable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.011"/>
  <testcase name="executeFailingRunnable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="0.0"/>
  <testcase name="submitFailingListenableRunnable" classname="org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests" time="1.004"/>
  <system-out><![CDATA[18:46:52.701 [test-1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.RuntimeException: intentional test failure
	at org.springframework.scheduling.concurrent.ThreadPoolTaskSchedulerTests$TestTask.run(ThreadPoolTaskSchedulerTests.java:183) ~[test/:?]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
18:46:53.973 [test-1] ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.RuntimeException: intentional test failure
	at org.springframework.scheduling.concurrent.AbstractSchedulingTaskExecutorTests$TestTask.run(AbstractSchedulingTaskExecutorTests.java:248) ~[test/:?]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_261]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
